### ISSUE TITLE
Plant update API: accept device id in MAC format

### ISSUE THREAD

**Issue by oluckyman** [buratinos/buratino-cloud#2]
Device will send `{"device": "xx:xx:xx:xx:xx:xx"}` in the body

**Comment by asobolev** [comment]
Using colons in URLs is safe - 
https://stackoverflow.com/questions/2053132/is-a-colon-safe-for-friendly-url-use

so we can keep it as a unique ID

**Comment by oluckyman** [comment]
sending this:
```
PUT http://buratino.asobolev.ru/api/v1/plants/11/

{
    "device": "30:AE:A4:1B:3D:48"
}
```
receiving 400 Bad Request response:
```
{
    "device": [
        "Invalid pk \"30:AE:A4:1B:3D:48\" - object does not exist."
    ]
}
```

`30:AE:A4:1B:3D:48` is the real ID of the esp-32 chip

**Comment by asobolev** [comment]
Yes - so before linking a device and a plant we need to have this device as a separate object in the database. So either I can create devices when I load test data (assuming in the future we load ALL produced devices in the production database ourselves) or the mobile app creates a new device (POST request) and links it to the plant (PUT request). Let's discuss which way is better!
