### ISSUE TITLE
Question: is it ok to register one device to different plants?

### ISSUE THREAD

**Issue by oluckyman** [buratinos/buratino-cloud#8]
Now when I register device to plant AAA, and then register the same device to plant BBB, both plants have the same device connected to them.

**Comment by asobolev** [comment]
Good question)

Physically one plant can have many devices in the same pot or ground (which is totally unreasonable but still), however several plants can be also in the same pot and have only one device. Which case is most reasonable, or should we allow both? Maybe should discuss with Andrey next time

**Comment by oluckyman** [comment]
To unregister device call Update Plant API with body:
```
{ device: null }
```

Maybe later add 'Unregister' button into mobile app if needed.
